vault_user: vault
vault_config_dir: /etc/vault.d
vault_config_file: /etc/vault.d/vault.hcl
vault_service_file: /etc/systemd/system/vault.service
#vault_repo_url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
vault_storage_path: /opt/vault/data
vault_listener_address: "0.0.0.0:8200"
vault_tls_disable: true
vault_ui: true
