name: Workstation Terraform AWS Deploy
on: [workflow_dispatch]
jobs:
  Workstation-Job:
    name: Terraform apply
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Terraform Init
        run: terraform init -backend-config=env/state.tfvars
  
      - name: Terraform Plan
        run: terraform plan -out=tfplan
  
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan

  Workstation-destroy-Job:
    name: Terraform destroy
    runs-on: ubuntu-latest
    needs: Workstation-Job
    environment: qa
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Plan
        run: terraform plan -out=tfplan
  
      - name: Terraform destroy
        run: terraform destroy -auto-approve 
